### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [linuxct/PhoneAccountDetector#1]
Nice to see this app! Can you also tell what license it falls under? Currently no license is mentioned (apart from in the gradle files), which generally means "all rights reserved" and "juristically risky to use the code" (or distribute the APK). So for the public good, a FOSS license would be great :wink:

**Comment by linuxct** [comment]
Hi @IzzySoft, I have added the [LICENSE](https://github.com/linuxct/PhoneAccountDetector/blob/main/LICENSE) file. The project is AGPL 3.0. Cheers!

**Comment by IzzySoft** [comment]
Wonderful, thank you! Starting with the next sync tomorrow around 7 pm UTC, your app will become available [here in my repo](https://apt.izzysoft.de/fdroid/index/apk/space.linuxct.phoneaccountdetector) (until then, the link will show a 404) to make it easier to find, install and keep updated. I've also added 2 screenshots (feel free to grab them for your Readme if you wish) and expanded the description a little (which you are also free to copy back).
