### ISSUE TITLE
bug: Status TextView layout is not centered 

### ISSUE THREAD

**Issue by linuxct** [linuxct/PhoneAccountDetector#10]
To be fixed.  
As seen on Galaxy Tab S7+ 
![image](https://user-images.githubusercontent.com/3966313/148953910-bc5493df-7550-4fb6-ab70-338486344d05.png)

**Comment by wacko1805** [comment]
Will look into this. Should be easy fix

**Comment by linuxct** [comment]
> Will look into this. Should be easy fix

Thank you! I was planning on looking at it this afternoon, just wrote it as a reminder. I will let you know if I manage to fix it 👍🏼

**Comment by linuxct** [comment]
Thank you @wacko1805!
