### ISSUE TITLE
"There was a problem parsing the app" errors (due to unsupported Android version) 

### ISSUE THREAD

**Issue by amalskyee** [linuxct/PhoneAccountDetector#3]
can't Install the app!

**Comment by linuxct** [comment]
You are trying to run the application on an unsupported (running a version lower than Android 10.0), and thus non-vulnerable system.  
Take into account that **only Android 10.0+ devices were originally supported** by this application, as the vulnerability only affects these devices.  

For the sake of test capabilities, as @lawtancool very well commented on #2, I am making this application compatible with Android 9.0+ devices in the next commit(s). But keep in mind, **this does not mean that Android 9.0 devices are vulnerable**.  

I hope this solves the doubts regarding all "There was a problem parsing the package" errors.

**Comment by linuxct** [comment]
Please check [tag "1.1"](https://github.com/linuxct/PhoneAccountDetector/releases/tag/1.1).
