### ISSUE TITLE
versionCode

### ISSUE THREAD

**Issue by IzzySoft** [linuxct/PhoneAccountDetector#4]
Please remember to [adjust versioning](https://github.com/linuxct/PhoneAccountDetector/blob/main/app/build.gradle#L13) when you prepare a new release. The APK at the current 1.1 release identifies as

    package: name='space.linuxct.phoneaccountdetector' versionCode='1' versionName='1.0'

Which means, it's presented to the user as Version 1.0 – and Android does not recognize it as update either as the `versionCode` was not increased. So users won't get an update notification either.

Thanks in advance!

**Comment by linuxct** [comment]
Hi @IzzySoft, noted with thanks. The change has been made and a new tag/release has been pushed (previous ones were deleted), hopefully this is not an issue for your F-Droid repo to track the changes (if so, I am open to push a new version, tag and release again). Thank you!

**Comment by IzzySoft** [comment]
Thanks a lot! And no, shouldn't be an issue because: the version it pulled today identified as 1.0, so it will look for 1.1 again tomorrow. Luckily you've updated that release, so it won't turn into an eternal loop :rofl:

To make sure, I've triggered the update manually – looks good!

BTW: would you like a PR with the metadata in [Fastlane structure](https://gitlab.com/snippets/1895688), so you're in control how your app is presented? Then I'd wrap that up (that's how metadata is stored on my end anyway).

**Comment by linuxct** [comment]
Perfect, glad it worked without doing anything extra. And sure, please do, I will merge it with no problems!

**Comment by IzzySoft** [comment]
Apologies for the delay, was busy on other tasks – but the reminder kept it awake, so it was not forgotten :smile:

**Comment by linuxct** [comment]
> Apologies for the delay, was busy on other tasks – but the reminder kept it awake, so it was not forgotten smile

No worries! I just merged it, thank you :)

**Comment by IzzySoft** [comment]
Thanks! I've updated your app's settings in my repo to check Fastlane whenever a new release is pulled – so now you're in control of what is shown :smile: Helpers for working on Fastlane:

* my [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688)
* my wiki with pointers for [formatting Fastlane description](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) for optimal effects :wink:

Thanks again for providing your app – and all the best for its (and your) future!
